# KlipperScreen instance shown on the Lerdge TFT (480x320), see
# https://klipperscreen.readthedocs.io/en/latest/Configuration/
[main]
font_size: small
show_cursor: False
use_dpms: False
screen_blanking: off
